### PR TITLE
#18 Forbid let and const usage

### PR DESCRIPTION
**Pull request by frsv**

### CODE REVIEW

**Comment by ai** [comment]
You forgot to update docs ;). Be more careful — on any change you should think, how it is affected to docs. Docs is the most important thing for open source project (more important than code).

**Comment by frsv** [comment]
@ai My bad, forget to do obvious things :)

**Comment by ai** [comment]
Done. Thanks. @lamartire you could continue.

**Comment by epszaw** [comment]
@ai, yay, thanks :smile_cat:

**Pull request merged**
