### PR TITLE
Remove strict rule

### PR DESCRIPTION
**Pull request by epszaw**

### CODE REVIEW

**Comment by epszaw** [comment]
For this logux/logux-server#19

**Comment by ai** [comment]
@frsv `const` is not safe :)

**Comment by ai** [comment]
Let’s remove `strict` and also force developers to use only `var`, instead of trending but not useful `const`. Could you make other PR?

**Comment by epszaw** [comment]
Sure.

**Comment by ai** [comment]
@lamartire this task was already done by @frsv

**Pull request closed without merging**
